### ISSUE TITLE
Stop demo on exit

### ISSUE THREAD

**Issue by christopolise** [NET-BYU/sss#14]
I am writing a demo that messes with memory management (in Python? The horror!). Everything is tied up nicely but I notice that the runners do not call stop on the current running demo before exiting. 

Fixing this in the simulator is easy enough (there is just one line to add before `sys.exit()`), but I feel like it might be a little more tricky for `kiosk` and `demo` when they are not running with the `-s` flag.

**Comment by philipbl** [comment]
@christopolise, we do call `stop()` in the runners:

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/demo.py#L63

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/kiosk.py#L117

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/kiosk.py#L141

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/kiosk.py#L151

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/simulator.py#L102

https://github.com/NET-BYU/sss/blob/412d4529087c569887620513b8fb25227e620b4e/runners/test.py#L35

Maybe I am misunderstanding the problem?

**Comment by christopolise** [comment]
I don't think I framed it the best. When exiting the simulator in `pygame`, regardless of where the demo is in its execution or where the runner is, when the signal to kill the program is called, a function (I believe) is called before exit. I don't know if the other runners have a function like that to catch a sigterm and run a demo.stop() type call on it...

**Comment by apal6981** [comment]
Are you looking for sigint and sigterm to be caught? Currently only the demo runner has any sort of sigint catching.

**Comment by christopolise** [comment]
Yes, and on that catch, to call stop on the current demo

**Comment by philipbl** [comment]
That makes sense. I will start working on that.
