### ISSUE TITLE
Simulation mode runs faster than demo mode

### ISSUE THREAD

**Issue by christopolise** [NET-BYU/sss#3]
From @codyarvonen:
> When running the command `python3 main.py simulator` to play the tetris game, the blocks fall like twice as fast as they do when running `python3 main.py demo tetris -s`. @apal6981

**Comment by apal6981** [comment]
I have run the simulator and demo side by side and they seem to behave the same. Maybe this got fixed with other updates. @philipbl any thoughts?

**Comment by philipbl** [comment]
Yeah, I need to try to reproduce this myself. My guess is that the simulator code and demo code are calling the pygame tick function slightly differently causing one to run faster than the other.

**Comment by christopolise** [comment]
This hasn't been an issue for a while, closing for now

**Comment by christopolise** [comment]
Doesn't seem to be an issue, but we'll keep an eye on it. Closing for now.
