### ISSUE TITLE
Page "Install SSS on Mac or Linux" - Bad git clone command.

### ISSUE THREAD

**Issue by doglman** [NET-BYU/sss#31]
I ran the clone from repository command in the "Installation" section:
`git clone git@github.com:NET-BYU/sss.git` and **it didn't work**. Error said I need to make sure I have the correct access rights and the repository exists.

Used `git clone https://github.com/NET-BYU/sss.git` instead.

**Suggestion**: Modify the command to be the one I used, or include enough details so I can avoid the error.

**Comment by christopolise** [comment]
This is using the SSH protocol instead of the HTTP protocol. This is a more secure and convenient method than HTTP which now requires a separate access token to be used every time. Could you please provide a copy of the error you see in the terminal when trying to run the command above?

**Comment by doglman** [comment]
```
$ git clone git@github.com:NET-BYU/sss.git
Cloning into 'sss'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by christopolise** [comment]
It turns out that SSH access implies that you have edit access and only SSH keypairs will be accepted by people in the organization. In view of that issue, I think it is a good catch to use HTTPS for public access.

**Comment by christopolise** [comment]
Fixed!
