### ISSUE TITLE
Page "Install SSS on Mac or Linux" - Unclear indicator of successfully entering the virtual environment.

### ISSUE THREAD

**Issue by doglman** [NET-BYU/sss#32]
In the section "Setting up SSS", there is a block-quote paragraph beginning with the phrase "You should notice the prompt of your terminal change to indicate..."

**It wasn't clear** what that was supposed to look like. It could have been as easy as saying you're prompt should now begin with `(venv)` like this: `(venv) username@host:~/sss`

**Suggestion**: Include a little more detail describing what the terminal prompt should change to look like, making it clearer that the user has indeed successfully entered the virtual environment.

**Comment by christopolise** [comment]
A specific indicator wasn't originally included because not everyone's default shell will be `bash` and that might cause some confusion.

However, an example and a more universal check to ensure you are in a virtual environment have been included in 7605bee.
