### ISSUE TITLE
Fix NetLab Flag to Center Logo

### ISSUE THREAD

**Issue by christopolise** [NET-BYU/sss#67]
**Describe the bug**
I think this is more of a visual bug. But the NET Lab logo was centered vertically for the sign when the demo was made, but then the sign doubled in height and the logo is awkwardly at the top of the flag. Lets center that sucker.

**To Reproduce**
1. Go to the `sss` folder
2. Activate the `venv` environment
3. run `python main -vvvvv demos netlab_flag -s`
4. Shudder in horror at the asymmetry

**Expected behavior**
Something a little more visually appealing

**Screenshots**
![Screenshot from 2024-10-23 15-42-49](https://github.com/user-attachments/assets/139c233c-d86c-4ac3-8d16-d7355ee184a9)
(Gross, right?)

**Comment by philipbl** [comment]
Are you sure that is not just a simulator problem? I think that bar is there because when you run main.py in simulator mode, it has a strip of buttons you can press to run each demo.

**Comment by christopolise** [comment]
I am referring to vertical symmetry, not horizontal :arrow_up_down:  >> :left_right_arrow:

**Comment by philipbl** [comment]
Oh, I see. I always thought that's how you guys designed it! 🙃

**Comment by christopolise** [comment]
Lol that's on me. It was in the vertical center when I first made it because the sign was only half as tall :stuck_out_tongue_winking_eye:

**Comment by christopolise** [comment]
This is the fix screenshot:

![image](https://github.com/user-attachments/assets/1ac5fe36-1d3e-4f65-868b-47f1c22b3b28)
